# Generated by Django 5.0.4 on 2024-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_book'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS lend_book (
             id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
             book_id UUID,
             borrow_date DATE,
             return_date DATE
             );"""),
            #  ("""""") if you want to add something for example like adding foreign keys
             ],
        reverse_sql=[
            # (""""""), if you want to add drop of something for example like adding foreign keys
            ("DROP TABLE IF EXISTS lend_book"),
            ]
            )
    ]
